version: '3.8'

services:
  api:
    build:
      context: ../server
      dockerfile: ../infra/Dockerfile.api
    ports:
      - "5175:5175"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5175
    volumes:
      - ../server:/app
      - /app/bin
      - /app/obj
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ../client
      dockerfile: ../infra/Dockerfile.client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:5175
    depends_on:
      - api
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
